backend: 
 name: git-gateway 
 branch: master # Branch to update (optional; defaults to master)
# This line should *not* be indented 
publish_mode: editorial_workflow

# This line should *not* be indented 
media_folder: "uploads" 

collections: 
 - name: "main" # Used in routes, e.g., /admin/collections/blog 
   label: "android" # Used in the UI	
   folder: "android" # The path to the folder where the documents are stored
   create: true # Allow users to create new documents in this collection
   slug: "{{slug}}" # Filename template, e.g., title.md
   fields: # The fields for each document, usually in front matter
    - {label: "Layout", name: "layout", widget: "hidden", default: "main"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Body", name: "body", widget: "markdown"}
 - name: "blog" # Used in routes, e.g., /admin/collections/blog 
   label: "blog" # Used in the UI 
   folder: "blog" # The path to the folder where the documents are stored 
   create: true # Allow users to create new documents in this collection 
   slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md 
   fields: # The fields for each document, usually in front matter
    - {label: "Layout", name: "layout", widget: "hidden", default: "main"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
    - {label: "Body", name: "body", widget: "markdown"}